# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_protoc import invoice_rpc_pb2 as invoice__rpc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in invoice_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InvoiceRpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.invoice_recognize = channel.unary_stream(
                '/invoice.InvoiceRpc/invoice_recognize',
                request_serializer=invoice__rpc__pb2.InvoiceRecognizeReq.SerializeToString,
                response_deserializer=invoice__rpc__pb2.InvoiceRecognizeResp.FromString,
                _registered_method=True)
        self.certificate_recognize = channel.unary_stream(
                '/invoice.InvoiceRpc/certificate_recognize',
                request_serializer=invoice__rpc__pb2.InvoiceRecognizeReq.SerializeToString,
                response_deserializer=invoice__rpc__pb2.InvoiceRecognizeResp.FromString,
                _registered_method=True)


class InvoiceRpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def invoice_recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def certificate_recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InvoiceRpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'invoice_recognize': grpc.unary_stream_rpc_method_handler(
                    servicer.invoice_recognize,
                    request_deserializer=invoice__rpc__pb2.InvoiceRecognizeReq.FromString,
                    response_serializer=invoice__rpc__pb2.InvoiceRecognizeResp.SerializeToString,
            ),
            'certificate_recognize': grpc.unary_stream_rpc_method_handler(
                    servicer.certificate_recognize,
                    request_deserializer=invoice__rpc__pb2.InvoiceRecognizeReq.FromString,
                    response_serializer=invoice__rpc__pb2.InvoiceRecognizeResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'invoice.InvoiceRpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('invoice.InvoiceRpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InvoiceRpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def invoice_recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/invoice.InvoiceRpc/invoice_recognize',
            invoice__rpc__pb2.InvoiceRecognizeReq.SerializeToString,
            invoice__rpc__pb2.InvoiceRecognizeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def certificate_recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/invoice.InvoiceRpc/certificate_recognize',
            invoice__rpc__pb2.InvoiceRecognizeReq.SerializeToString,
            invoice__rpc__pb2.InvoiceRecognizeResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
